# Generated by Django 2.2.11 on 2020-03-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200327_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='必須。140字以内。', max_length=140, verbose_name='プロダクト説明'),
        ),
    ]
