# Generated by Django 2.2.11 on 2020-04-02 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20200327_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='cms.ProjectUserRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
